import { define_crud, define_module } from "@opus-perpetuus/imperium-core-kit";
import { dynamic_dashboard_pages } from "./dynamic-dashboard.pages.ts";
import { dynamic_dashboard_tables } from "./dynamic-dashboard.tables.ts";

export const dynamic_dashboard_module = define_module({
  resource: "dynamic-dashboard",
  labels: {
    singular: "Tableros dinámicos",
    plural: "Tableros dinámicos",
    read: "Ver Tableros dinámicos",
    write: "Editar Tableros dinámicos",
  },
  routes: define_crud({
    resource: "dynamic-dashboard",
    table: "dynamic_dashboard",
    soft_delete: true,
    soft_delete_field: "is_active",
    history: true,
    default_sort: "name:asc",
    id_prefix: "dynamic-",
    fields: {
      name: { type: "string", required: true, search: true },
      description: { type: "string", search: true },
      is_active: { type: "boolean" },
      state: { type: "string" },
      ref: { type: "string", search: true },
      search_field: { type: "string", search: true },
      created_by: { type: "string" },
      custom_data: { type: "json" },
      payload: { type: "json" },
      is_global: { type: "boolean" },
      widget_type: { type: "string", search: true },
      title: { type: "string", search: true },
      model_id: { type: "string", search: true },
      domain: { type: "string", search: true },
      fields: { type: "json" },
      group_by: { type: "string", search: true },
      group_by_date_granularity: { type: "string", search: true },
      op: { type: "string", search: true },
      field: { type: "string", search: true },
      date_field: { type: "string", search: true },
      mode: { type: "string", search: true },
      relative: { type: "string", search: true },
      from: { type: "string", search: true },
      to: { type: "string", search: true },
      target_value: { type: "number" },
      target_date: { type: "string", search: true },
      x: { type: "number" },
      y: { type: "number" },
      cols: { type: "number" },
      rows: { type: "number" },
      order: { type: "number" },
      visible: { type: "boolean" },
      widgets: { type: "json" },
    },
    options_map: { value: "id", label: "name" },
  }),
  tables: dynamic_dashboard_tables,
  pages: dynamic_dashboard_pages,
  menu: [
    {
      id: "tableros-dinamicos.dynamic-dashboard",
      label: "Tableros dinámicos",
      order: 10,
      pageId: "tableros-dinamicos.dynamic-dashboard",
      path: "dynamic-dashboard",
      permission: "subject.tableros-dinamicos.dynamic-dashboard.read",
      icon: "document",
    }
    ],
});
