import type { KirletTableDecl } from "@opus-perpetuus/imperium-core-kit";

export const dynamic_dashboard_tables: KirletTableDecl[] = [
  {
    name: "dynamic_dashboard",
    columns: [
      { name: "id", type: "text", primaryKey: true },
      { name: "name", type: "text", notNull: true },
      { name: "description", type: "text" },
      { name: "is_active", type: "boolean", notNull: true, default: true },
      { name: "state", type: "text" },
      { name: "ref", type: "text", unique: true },
      { name: "search_field", type: "text" },
      { name: "created_by", type: "text" },
      { name: "custom_data", type: "json" },
      { name: "payload", type: "json" },
      { name: "created_at", type: "text", notNull: true },
      { name: "updated_at", type: "text", notNull: true },
      { name: "is_global", type: "boolean" },
      { name: "widget_type", type: "text" },
      { name: "title", type: "text" },
      { name: "model_id", type: "text" },
      { name: "domain", type: "text" },
      { name: "fields", type: "json" },
      { name: "group_by", type: "text" },
      { name: "group_by_date_granularity", type: "text" },
      { name: "op", type: "text" },
      { name: "field", type: "text" },
      { name: "date_field", type: "text" },
      { name: "mode", type: "text" },
      { name: "relative", type: "text" },
      { name: "from", type: "text" },
      { name: "to", type: "text" },
      { name: "target_value", type: "real" },
      { name: "target_date", type: "text" },
      { name: "x", type: "real" },
      { name: "y", type: "real" },
      { name: "cols", type: "real" },
      { name: "rows", type: "real" },
      { name: "order", type: "real" },
      { name: "visible", type: "boolean" },
      { name: "widgets", type: "json" },
    ],
    indexes: [
      { name: "idx_dynamic_dashboard_name", columns: ["name"] },
      { name: "idx_dynamic_dashboard_active", columns: ["is_active"] },
    ],
  },
];
